<?php $helper = $this->helper('Celebros\ConversionPro\Helper\Data') ?>
<?php if ($helper->getAddScripts() && $helper->getScriptsLocation() == 'body'): ?>
<?php $scripts = $helper->getExternalJsUrls(); ?>
<script type="text/javascript">
    require(["jquery", "<?php echo $scripts[1] ?>"], function(){
		UITClientConfigMaster.Initlize();
    });
</script> 
<?php endif ?>
<?php if ($helper->getAddDiv()) : ?>
<div id="<?php echo $block->escapeHtml($helper->getProductListContainerId()) ?>"></div>
<?php endif ?>
